services:
  postgres:
    image: postgres:16
    container_name: ImageManager-Postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: ImageManager-App
    restart: always
    ports:
      - "8080:5000"
    env_file:
      - .ENV
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/postgres
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
